version: "3.3"
services:
  jfrog:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - "8081:8081"
  android:
    environment:
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
    build: .
    container_name: ajcontainer
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - android_sdk:/usr/share/jenkins/ref/sdk
    depends_on:
      - jfrog
volumes:
  jenkins_home:
  android_sdk: